#!/usr/bin/env bash
# commands to install nginx on the web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Ngnix HTTP'

echo "Hello World!" | sudo tee/var/www/html/index.html

# testing ngnix configurations
sudo nginx -t

sudo service nginx reload
