#!/usr/bin/env bash
# Commands to install Nginx on Web-Sever-01
# Update Packages
sudo apt-get update
sudo apt-get -y install nginx

# allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html
# check Syntax errors
sudo nginx -t

# Restarting Nginx
sudo service nginx start
