#!/usr/bin/env bash
# This script Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
sudo apt-get update
apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

server_config=\
"
frontend  my_web-frontend
        bind *:80
        mode http
        default_backend my_web-backend
backend my_web-backend
        balance roundrobin
        server 358495-web-01 54.90.37.246 check
        server 358495-web-02 54.237.2.142 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
