#!/usr/bin/env bash
# a bash script that pings an IP address passed as an argument
# it should throw usage error if argument has no IP address
# ping the IP 5 times

if [ "$#" -ne 1]; then 
echo "usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
ping -c 5 "$1"

fi
